[GR-49835] Ensure __text section exists
We changed the linker from `ld64` to `ld64.ld` in the Sulong toolchain.
Building of libR.dylib is a bit special:

```
$ /Users/graal1/slave/e/graal/sulong/mxbuild/darwin-amd64/SULONG_BOOTSTRAP_TOOLCHAIN/bin/graalvm-native-clang -dynamiclib -Wl,-headerpad,80000  -single_module -multiply_defined suppress  -L/cm/shared/apps/bzip2/1.0.6/lib -L/cm/shared/apps/xz/5.2.2/lib -L/cm/shared/apps/pcre2/pcre2-10.37/lib -L/cm/shared/apps/curl/7.50.1/lib -L/cm/shared/apps/gcc/10.2.0/lib -L/usr/lib -Wl,-rpath,@loader_path/ -o /Users/graal1/slave/e/main/lib/libR.dylib -L/Users/graal1/slave/e/main/lib -lRblas -lRlapack -current_version 4.0.3 -compatibility_version 4.0.3
```

It does not contain any code, it is just a "dummy library" to express dependencies.  Later on the shared library id is updated via `install_name_tool`, but that one fails due to:

```
$ install_name_tool -id @rpath/libR.dylib /Users/graal2/slave/e/fastr/lib/libR.dylib
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: /Users/graal2/slave/e/fastr/lib/libR.dylib (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)
```

The difference is that `ld64` used to insert an empty `__TEXT,__text` section:

```
$ otool -l ld64/libR.dylib
ld64/libR.dylib:
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 152
  segname __TEXT
   vmaddr 0x0000000000000000
   vmsize 0x0000000000081000
  fileoff 0
 filesize 528384
  maxprot 0x00000007
 initprot 0x00000005
   nsects 1
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x0000000000081000
      size 0x0000000000000000
    offset 528384
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x0000000000081000
   vmsize 0x0000000000001000
  fileoff 528384
 filesize 48
  maxprot 0x00000007
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 2
```

while `ld64.lld` does not do that:

```
otool -l ld64.lld/libR.dylib
lld/libR.dylib:
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __TEXT
   vmaddr 0x0000000000000000
   vmsize 0x0000000000081000
  fileoff 0
 filesize 528384
  maxprot 0x00000005
 initprot 0x00000005
   nsects 0
    flags 0x0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x0000000000081000
   vmsize 0x0000000000000030
  fileoff 528384
 filesize 48
  maxprot 0x00000001
 initprot 0x00000001
   nsects 0
    flags 0x0
```

But then `install_name_tool` will trip over it as it expects an section there, see:
https://github.com/opensource-apple/cctools/blob/fdb4825f303fd5c0751be524babd32958181b3ed/misc/install_name_tool.c#L763-L778
https://github.com/opensource-apple/cctools/blob/fdb4825f303fd5c0751be524babd32958181b3ed/misc/install_name_tool.c#L842-L849

As a workaround we just force the linker to always create that section via `-add_empty_section`:

```
     -add_empty_section segname sectname
             An empty section named sectname in the segment segname. If any of the inputs
             contains a section (segname,sectname), that section will be included in the
             output, and this option will be ignored.
```